BEGIN;

CREATE SCHEMA IF NOT EXISTS ai_processing;

CREATE TABLE IF NOT EXISTS ai_processing.ai_processing_jobs (
    id uuid PRIMARY KEY,
    scan_id varchar(255) NOT NULL,
    processing_version varchar(100) NOT NULL,
    requester_user_id varchar(255) NOT NULL,
    member_id varchar(255) NOT NULL,
    business_profile_id varchar(255) NOT NULL,
    status varchar(32) NOT NULL,
    attempt_count integer NOT NULL DEFAULT 0,
    max_attempts integer NOT NULL DEFAULT 3,
    lease_owner varchar(255),
    lease_token uuid,
    lease_expires_at timestamptz,
    heartbeat_at timestamptz,
    next_attempt_at timestamptz NOT NULL DEFAULT now(),
    result_ref varchar(255),
    failure_code varchar(100),
    trace_id varchar(255) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    completed_at timestamptz,
    CONSTRAINT ai_processing_jobs_status_check
        CHECK (status IN (
            'accepted', 'queued', 'processing', 'completed',
            'failed_retryable', 'failed_terminal'
        )),
    CONSTRAINT ai_processing_jobs_attempt_count_check
        CHECK (attempt_count >= 0 AND attempt_count <= max_attempts),
    CONSTRAINT ai_processing_jobs_max_attempts_check
        CHECK (max_attempts BETWEEN 1 AND 10),
    CONSTRAINT ai_processing_jobs_completed_at_check
        CHECK ((status = 'completed') = (completed_at IS NOT NULL)),
    CONSTRAINT ai_processing_jobs_lease_check
        CHECK (
            status <> 'processing'
            OR (lease_owner IS NOT NULL AND lease_token IS NOT NULL
                AND lease_expires_at IS NOT NULL AND heartbeat_at IS NOT NULL)
        ),
    CONSTRAINT ai_processing_jobs_scan_version_unique
        UNIQUE (scan_id, processing_version)
);

CREATE INDEX IF NOT EXISTS ai_processing_jobs_dispatch_idx
    ON ai_processing.ai_processing_jobs (status, next_attempt_at, created_at)
    WHERE status IN ('accepted', 'failed_retryable', 'queued');

CREATE INDEX IF NOT EXISTS ai_processing_jobs_expired_lease_idx
    ON ai_processing.ai_processing_jobs (lease_expires_at, updated_at)
    WHERE status = 'processing';

CREATE INDEX IF NOT EXISTS ai_processing_jobs_workspace_idx
    ON ai_processing.ai_processing_jobs (business_profile_id, created_at);

CREATE TABLE IF NOT EXISTS ai_processing.ai_processing_attempts (
    id uuid PRIMARY KEY,
    job_id uuid NOT NULL REFERENCES ai_processing.ai_processing_jobs(id),
    attempt_number integer NOT NULL,
    worker_id varchar(255) NOT NULL,
    lease_token uuid NOT NULL,
    started_at timestamptz NOT NULL,
    finished_at timestamptz,
    outcome varchar(32),
    error_code varchar(100),
    error_type varchar(100),
    CONSTRAINT ai_processing_attempts_number_check
        CHECK (attempt_number >= 1),
    CONSTRAINT ai_processing_attempts_outcome_check
        CHECK (outcome IS NULL OR outcome IN (
            'completed', 'failed_retryable', 'failed_terminal', 'lease_expired'
        )),
    CONSTRAINT ai_processing_attempts_unique
        UNIQUE (job_id, attempt_number)
);

CREATE INDEX IF NOT EXISTS ai_processing_attempts_job_idx
    ON ai_processing.ai_processing_attempts (job_id, attempt_number);

CREATE TABLE IF NOT EXISTS ai_processing.ai_processing_outbox (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_key varchar(255) NOT NULL,
    job_id uuid NOT NULL REFERENCES ai_processing.ai_processing_jobs(id),
    event_type varchar(100) NOT NULL,
    payload jsonb NOT NULL,
    available_at timestamptz NOT NULL DEFAULT now(),
    attempt_count integer NOT NULL DEFAULT 0,
    locked_by varchar(255),
    locked_until timestamptz,
    delivered_at timestamptz,
    last_error_code varchar(100),
    CONSTRAINT ai_processing_outbox_event_key_unique
        UNIQUE (event_key),
    CONSTRAINT ai_processing_outbox_attempt_count_check
        CHECK (attempt_count >= 0)
);

CREATE INDEX IF NOT EXISTS ai_processing_outbox_claim_idx
    ON ai_processing.ai_processing_outbox (available_at, id)
    WHERE delivered_at IS NULL;

CREATE INDEX IF NOT EXISTS ai_processing_outbox_job_idx
    ON ai_processing.ai_processing_outbox (job_id, id);

CREATE TABLE IF NOT EXISTS ai_processing.ai_worker_leases (
    worker_id varchar(255) PRIMARY KEY,
    lease_token uuid NOT NULL,
    capacity integer NOT NULL DEFAULT 1,
    active_slots integer NOT NULL DEFAULT 0,
    heartbeat_at timestamptz NOT NULL,
    lease_expires_at timestamptz NOT NULL,
    draining boolean NOT NULL DEFAULT false,
    worker_version varchar(255) NOT NULL,
    CONSTRAINT ai_worker_leases_capacity_check
        CHECK (capacity >= 1 AND active_slots >= 0 AND active_slots <= capacity)
);

COMMENT ON TABLE ai_processing.ai_processing_jobs IS
    'Canonical durable AI processing job state; broker delivery is not authoritative.';
COMMENT ON TABLE ai_processing.ai_processing_outbox IS
    'Transactional dispatch/effect events; payload is restricted to reference/status metadata.';

COMMIT;
